### PR TITLE
fix link, make independant from protocol

### PR DESCRIPTION
**Pull request by robertkowalski**

### CODE REVIEW

**Comment by mikeal** [comment]
This won't work, that resource has a bad SSL cert because of the domain. Change the domain to "go.pardot.com" and it should work.

**Comment by robertkowalski** [comment]
@mikeal aw, thanks! fixed!

**Comment by mikeal** [comment]
+1 to merge.

**Comment by robertkowalski** [comment]
the form does not load in my chrome, i am going to revert both commits for now, ok?

**Comment by mikeal** [comment]
i have it working locally, what error are you getting?

**Comment by robertkowalski** [comment]
oh wow - the form gets blocked by my ad blocker "disconnect"

**Comment by robertkowalski** [comment]
merged as 53ef6105c83ee94018997c120dafb4798f7f1891 and online on nodejs.org now (except for disconnect users)

**Comment by fhemberger** [comment]
Doesn't work for Ghostery or AdblockPlus users as well! (So I guess a _lot_ of people won't see this at all)

**Comment by robertkowalski** [comment]
@mikeal is that a thing we can raise at the linux foundation or pardot?

**Pull request closed without merging**
