### PR TITLE
Add minutes for 04-30-2015 meeting

### PR DESCRIPTION
**Pull request by misterdjules**
/cc @joyent/node-coreteam @geek @robertkowalski.

### CODE REVIEW

**Comment by misterdjules** [comment]
@geek Thank you!

Just out of curiosity, is there a reason why it was merged with the git merge button rather than with [git-apply-pr](https://github.com/joyent/git-apply-pr)? If using git-apply-pr is too annoying, we can maybe make it easier to use, as I would like to avoid having a lot of unnecessary merge commits.

Thoughts?

**Comment by geek** [comment]
For the website there isn't a lot of advantage.  The green button works well for this repo.  @robertkowalski agrees, right?

**Comment by Fishrock123** [comment]
> as I would like to avoid having a lot of unnecessary merge commits.

While I also prefer this, we at the io.js website also settled on just using the green button.

**Comment by robertkowalski** [comment]
I am a fan of git-apply-pr but I also don't mind if Wyatt wants to use the
green button for the website.

**Pull request merged**
