### PR TITLE
update NodeSource logo

### PR DESCRIPTION
**Pull request by julianduque**
I work for NodeSource and we want to update our logo, thanks

### CODE REVIEW

**Comment by indexzero** [comment]
No opposition, but could you share a screenshot of what it looks like with the change? We may want to flow differently. This is current:

screen shot 2015-06-16 at 3 08 16 pm

Having done the "logo potpourri" for [several](http://2015.empirejs.org/#sponsors) [confs](http://2014.empirenode.org/#/sponsors) it's sometimes nice to have sponsor logos at a certain tier with all vertical or all horizontal logos for flow reasons. 

Other thoughts?

**Comment by julianduque** [comment]
Sure

**Comment by indexzero** [comment]
Sort of breaks the clean horizontal line that flowed before, don't you think?

**Comment by rvagg** [comment]
there's nothing clean about this table and in the current version the NS logo gets lost in antialiasing because of the horizontal restriction

+1, please merge this

**Comment by indexzero** [comment]
If the anti-aliasing is the issue then why not just make it wider? Then it would be larger and avoid the problem while having a straight line.

I believe you have merge authority. As I said to begin with I dont oppose it, but it certainly breaks the line of horizontal logos which is objectively more appealing. Yes the Silver level is quite messy but (for example) all of the Platinum logos are all vertical stacks with similar aspect ratios.

**Comment by rvagg** [comment]
I don't have merge authority, NS is a member and would like to update their logo, it's that simple. If you feel strongly about the layout then please update the GoDaddy logo too.

Ideally it'd be nice to have someone with some proper design skills to work on this page, I might go bother the website WG about this.

**Comment by indexzero** [comment]
This isn't an exercise in logo jockeying. I'm disappointed you would suggest that. It's beneath you to do so.

**Comment by Fishrock123** [comment]
For posterity: We need logo size guidelines before this turns into a bigger logo war.

**Comment by Fishrock123** [comment]
Note: I'm not accusing that of being the case, but it would definitely be prudent to set guidelines anyways.

**Comment by jasnell** [comment]
Guidelines are a Good Thing. When I first put this together I was given several possible logo options for NodeSource and just picked one at random. In general, however, if a member wants their logo changed, we change the logo, there shouldn't ever be any debate about it. Guidelines help everyone.

**Pull request merged**
