### PR TITLE
Add link to 2015-04-24-2 minutes 

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by misterdjules** [comment]
The commit message has some formatting issues and typos: I'd suggest changing `Add link in indext to minutes2015-04-24-2` to `Add link to 2015-04-24 minutes`.

Otherwise LGTM.

**Comment by mhdawson** [comment]
Fixed commit comment

**Comment by misterdjules** [comment]
LGTM, thank you!

**Comment by misterdjules** [comment]
Landed in 195863476e0ab94a29b9def2a922ccc6b270d427 and deployed at https://nodejs.org/about/core-team/meetings/2015-04-24/minutes.html, thank you again @mhdawson!

**Pull request closed without merging**
