### PR TITLE
Homepage: Notification about critical security release

### PR DESCRIPTION
**Pull request by fhemberger**
See https://github.com/nodejs/iojs.org/issues/397 and https://iojs.org/en/index.html.
Can we get this online quickly? /cc @nodejs/website @misterdjules

### CODE REVIEW

**Comment by rvagg** [comment]
Screenshot copied from original issue:

nodejs.org

Great work @fhemberger, lgtm, do we have other website wg members awake that can approve?

**Comment by fhemberger** [comment]
Maybe @robertkowalski, but here it's 8:00am on Saturday, so it still might take a bit. ;)
But if we need to get this out ASAP, I should be able to deploy to nodejs.org as well. Just let me know.

**Comment by fhemberger** [comment]
After talking with @rvagg, I decided to deploy this into master. It can still be changed afterwards, but we need to get the new version out now.

v0.12.6 is now live on nodejs.org

**Comment by bnb** [comment]
The image is wrong - it should say 0.12.6. Does it say that in production or not?

**Comment by fhemberger** [comment]
The image was just a quick mock I did in DevTools, in production it's v0.12.6, which is the correct release.

**Comment by robertkowalski** [comment]
uh sorry, was lying sick at >30°C in my bed since wednesday afternoon and still not feeling super healthy. after taking a look at master and nodejs.org this seems to be merged and deployed. +1 from me anyway.

**Comment by bnb** [comment]
This seems to be resolved - closing.

**Pull request closed without merging**
