### PR TITLE
Adding One-Shot Budapest

### PR DESCRIPTION
**Pull request by gergelyke**

### CODE REVIEW

**Comment by gergelyke** [comment]
ping @tjfontaine :)

**Comment by geek** [comment]
@gergelyke sorry this never got merged in... do you think at this point we should link to http://oneshot.nodeconf.com/ since that contains links to the other one-shot conferences?

**Comment by gergelyke** [comment]
No worries!
Yepp, that would be better

**Comment by geek** [comment]
Closing in favor of #59

**Pull request closed without merging**
