### PR TITLE
Adding apigee as a member of the foundation.

### PR DESCRIPTION
**Pull request by mikeal**
Apigee has joined the foundation as a silver member.

I don't know the process for building and testing this but I copied the format of the other members exactly.

### CODE REVIEW

**Comment by robertkowalski** [comment]
I noticed that all the member logos for silver are 200 / 203px wide, but this logo is just 166px

**Comment by mikeal** [comment]
@robertkowalski I figured that these were getting handled in CSS since they were so uniform. Should we adjust the width in CSS or in the image?

**Comment by robertkowalski** [comment]
it would be cool to have the image at least at 200px so we don't have to scale them up by using css, as they start to pixelate when manually scaling up pngs (it is not lossless)

scaling down is ok but scaling up makes images blurry/pixelated @mikeal

**Comment by mikeal** [comment]
@robertkowalski ahh, I read that backwards :) updated with better logo :)

**Comment by fhemberger** [comment]
LGTM, merged.

**Pull request merged**
