### PR TITLE
Use https for download links

### PR DESCRIPTION
**Pull request by fhemberger**

### CODE REVIEW

**Comment by misterdjules** [comment]
Thank you @fhemberger!

/cc @joyent/node-website

**Comment by indexzero** [comment]
I am +1 on this.

**Comment by misterdjules** [comment]
LGTM, landing and deploying soon.

**Comment by misterdjules** [comment]
Landed in ba61d5cc9950cce895e378e13b4ff6e7e9e9fd7a and deployed. Thank you @fhemberger :+1:

**Comment by misterdjules** [comment]
@indexzero I'm sorry I missed to mention you in the Reviewed-By field. I'm not used to pass `--plusone` when using `git-apply-pr` to merge PRs, and thus it only caught my review, not yours.

**Pull request closed without merging**
