### PR TITLE
Added basic /security page with disclosure info

### PR DESCRIPTION
**Pull request by evilpacket**
This is a security bug reporting / disclosure process / policy / info page. It lives at /security.
- Added security to the nav bar.
- Policy specifics are up for discussion but it's a pretty standard policy, based on other projects, specifically rails and ember.js.

To be discussed.
- We should establish a PGP key for people that want to use that for reporting issues.
- Primary and Secondary coordinators were arbitrarily set based on the list of core members. Who should that really be?
- Do we only need to request a CVE or should we also notify distros@openwall mailing list?

### CODE REVIEW

**Comment by TooTallNate** [comment]
Seems like a good idea to me.

**Comment by indexzero** [comment]
:+1:

**Comment by tjfontaine** [comment]
hey @evilpacket mind rebasing this into the markdown version, or would you rather I do that?

**Comment by evilpacket** [comment]
oh cool I think I totally screwed that up. argh. I had to change and remove all the nav stuff I had going, but the security.md file is there. If you want me to just resubmit a pr from a clean branch that's fine. Not sure what the hell happened. I'm bad at git :/

**Comment by evilpacket** [comment]
Any thoughts on getting this merged and establishing a solid, publicly
documented and communicated security strategy?

Timothy J Fontaine wrote:

**Comment by max-mapper** [comment]
Bump! This is important and should get merged.

**Comment by ryanj** [comment]
:+1:

**Comment by geek** [comment]
@evilpacket can you redo this PR, it can't be merged and modifies a lot of files :/

**Comment by evilpacket** [comment]
Yeah I sure can. Thx I'm bad at git and it got messy when the site was in so much flux.

**Comment by tjfontaine** [comment]
really just want the `security/index.md` file, also can you reformat on 80 columns that'd be fantastic :)

**Comment by evilpacket** [comment]
Yeah the rebase before messed about. I'll close this one and do another. Thx.

**Comment by evilpacket** [comment]
Closing in favor for this, more simple pr. https://github.com/joyent/node-website/pull/60

**Pull request closed without merging**
