### PR TITLE
blog: make blog mobile friendly

### PR DESCRIPTION
**Pull request by johnbrett**
blog: make blog mobile friendly

Currently the blog is not mobile optimized, making
for tough viewing from mobile devices. This commit
makes it mobile friendly. CSS added is scoped to the
blog only, other pages will not appear any differently.

### CODE REVIEW

**Comment by fitzage** [comment]
I haven't actually tested it, but the changes look fine.

[by which I mean I am a CSS expert, and this looks like it will behave as described]

**Comment by johnbrett** [comment]
If there's anything more I can do on this let me know, thanks for looking into it @misterdjules @fitzage

**Comment by misterdjules** [comment]
@johnbrett We would need someone to test it and report the test results. I find it's generally good practice to have someone who didn't write the code to test changes, as they have not any bias and find more ways to break it.

**Comment by misterdjules** [comment]
@joyent/node-website Is anyone available to test these changes?

**Comment by fhemberger** [comment]
I reviewed the changes and made two minor adjustments.
@johnbrett Thanks for pointing this out!

**Comment by johnbrett** [comment]
@fhemberger no thanks needed! glad I'll be able to read the blog on my phone now - thanks for reviewing and merging!

**Comment by johnbrett** [comment]
Hi @fhemberger, did this make it to the node website yet? Not seeing any change viewing the blog on mobile as of yet!

**Comment by fhemberger** [comment]
Unfortunately not, I can merge PRs but I cannot update the website yet. Waiting for @misterdjules or @robertkowalski …

**Comment by misterdjules** [comment]
@johnbrett The changes in this PR have been deployed at around 4am PDT, could you please check back and let us know if you see them live at nodejs.org?

**Comment by fhemberger** [comment]
@misterdjules @johnbrett I just checked: LGTM!

**Comment by misterdjules** [comment]
@fhemberger Thank you!

**Comment by johnbrett** [comment]
Thanks @misterdjules @fhemberger! Looks good!

**Pull request merged**
