### PR TITLE
website: additional platforms

### PR DESCRIPTION
**Pull request by jasnell**
Listing the ppc and system z builds on the downloads page.

The wording can be better but it's a start.

### CODE REVIEW

**Comment by robertkowalski** [comment]
Cool!

**current**:

bildschirmfoto 2015-03-28 um 14 30 19

what do you think of adding a class with `text-align: center` to the table?

e.g.:

bildschirmfoto 2015-03-28 um 14 31 00

**Comment by jasnell** [comment]
That works. Want me to add it to the PR?

**Comment by robertkowalski** [comment]
If you also agree that it is a good idea, then yes (disclaimer: I am no designer) :)

**Comment by jasnell** [comment]
Pushed the additional change

**Comment by robertkowalski** [comment]
minor thing: can you add it to https://github.com/joyent/node-website/blob/master/doc/pipe.css as a class?

**Comment by jasnell** [comment]
Done.

**Comment by robertkowalski** [comment]
LGTM

**Comment by robertkowalski** [comment]
merged as d29b6965ddd239fa5465e7c5493f42db7a7aad9e and already deployed :)

thank you!

**Pull request closed without merging**
