### PR TITLE
Changes Copyright Year

### PR DESCRIPTION
**Pull request by frankcash**
Changes copyright year from `2014` to `2015`

### CODE REVIEW

**Comment by robertkowalski** [comment]
+1

**Comment by tjhorner** [comment]
:+1:

You gonna get this commit hash tattooed if it gets merged?

**Comment by frankcash** [comment]
I know this isn't the most important commit but we are almost a month into 2015 :person_frowning:

**Comment by tjfontaine** [comment]
landed in 366cc2630f7e4d9148658b7bcd8e70d211dcc125

**Pull request closed without merging**
