### PR TITLE
Add meta viewport, improve mobile view

### PR DESCRIPTION
**Pull request by fhemberger**
After going through #117 I thought it might be a good idea to do a very basic check for a mobile view of the site in general. So I added the meta viewport tag to all html templates as well and did some quick fixes to make the pages at least readable on mobile.

### CODE REVIEW

**Comment by fhemberger** [comment]
_grmpf_ Don't know why this can't be merged automatically. Rebased against current master, but the Git gods are not with me this time. Anyways, 0c55c11 is of interest here and should be fairly easy to merge.

**Comment by fhemberger** [comment]
Ok, fixed the PR, good to merge.

**Comment by misterdjules** [comment]
Thank you @fhemberger :+1: 

/cc @joyent/node-website 

@fhemberger Please remember to /cc @joyent/node-website in every PR so that everyone on the team get a notification and at least someone can review it. Thank you! :+1:

**Comment by misterdjules** [comment]
@fhemberger Also please note that I'm not using ":+1" as a way to review and approve PRs, so I'm not saying that I reviewed these changes in my latest comments. Sorry for the confusion.

**Comment by fhemberger** [comment]
Okay. ;) Will add /cc for the next PRs.

**Comment by fhemberger** [comment]
Can someone please review these changes for mobile so we can get this merged? /cc @nodejs/website

**Comment by fhemberger** [comment]
Ok, one month without any objections, merging this …

**Pull request merged**
