### PR TITLE
Trademark policy & By-laws

### PR DESCRIPTION
**Pull request by mikeal**
This is the latest trademark policy, footer text, and by-laws as approved by the foundation's board.

### CODE REVIEW

**Comment by rvagg** [comment]
lgtm fwiw

**Comment by mikeal** [comment]
waiting for someone with access to refresh the servers like @robertkowalski to merge :)

**Comment by fhemberger** [comment]
@mikeal Sorry for keeping you waiting, hadn't seen this one … just deploying the changes.

**Comment by mikeal** [comment]
awesome, thanks :)

**Pull request merged**
